server:
  port: 10005
  servlet:
    context-path: /servant

spring:
  datasource:
    url: jdbc:mysql://cgbd-database:3306/civilservant?useSSL=false&allowMultiQueries=true #&serverTimezone=UTC 设置时区
    username: root
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      # 连接池设置，应用所有数据源中
      initialSize: 1
      minIdle: 1
      maxActive: 5
      # 获取连接等待超时的时间
      maxWait: 60000
      # 间隔多久进行检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 5
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      logSlowSql: true
      #通过connectProperties属性来打开mergeSql功能, 记录慢Sql时间设置, 即执行时间大于5000毫秒的都是慢sql
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      #过滤器，排除一些文件的监控
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #监控登录的一些设置，使用默认就好
      #stat-view-servlet:
        #enabled: true
        #url-pattern: /druid/*
        #reset-enable: true
        #login-username: root
        #login-password: 123456

  # REDIS (RedisProperties 单节点)
  redis:
    # Redis服务器地址
    host: cgbd-database
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ${CGBD_CONFIG_PASSWORD}
    # Redis数据库索引（默认为0）
    database: 1
    # 连接超时时间（毫秒）
    timeout: 1000
    # redis 过期时间 2小时
    expiration: 2
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1

mapper:
  mappers:
    com.edu.cgbd.base.MapperBase
mybatis:
  type-aliases-package: com.edu.cgbd.domain.servant
  mapper-locations: classpath:mapper/*Mapper.xml

#日志，使用自定义配置（logback-spring.xml）
#logging:
#  # 默认就说这个配置，可不配置
#  file: logback-spring.xml
#  root:
#    WARN
#  level:
#    org:
#      hibernate: ERROR
#      springframework:
#        web: DEBUG


#druid:
#  filter:
#    commons-log:
#      #data-source-log-enabled: true
#      statement-log-enabled: true
#      statement-executable-sql-log-enable: true

#redis集群配置
#  redis:
#    database: 0
#    # 集群设置 begin
#    cluster:
#      nodes:
#        - 10.217.17.70:7000
#        - 10.217.17.74:7000
#        - 10.217.17.75:7000
#      max-redirects: 3 # 获取失败 最大重定向次数
#    #集群设置 end
#    #单节点 begin
#    #    host: 10.217.17.74
#    #    port: 7000
#    #单节点 end
#    lettuce:
#      pool:
#        max-wait: 100000
#        max-idle: 10
#        max-active: 100
#    timeout: 5000
